name: Test fasmarm hello world

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run without codesign
        run: |
          chmod +x mc.bin
          ./mc.bin
